LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
    LOCAL_MODULE := magisk_prebuilt
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_CLASS := ETC
    LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)
    CUSTOMFEATURES_PATH := $(TARGET_RECOVERY_ROOT_OUT)/customfeatures
    MAGISK_VERSION_1 := Original
    MAGISK_VERSION_2 := Delta
    MAGISK_VERSION_3 := Alpha
    LOCAL_POST_INSTALL_CMD := \
        $(LOCAL_PATH)/magisk_prebuilt.sh $(CUSTOMFEATURES_PATH) $(MAGISK_VERSION_1) $(MAGISK_VERSION_2) $(MAGISK_VERSION_3);
include $(BUILD_PHONY_PACKAGE)